[package]
name = "uptime"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xv6_defs = { path = "../../xv6_defs" }
xv6_ulib = { path = "../xv6_ulib" }
